[package]
name = "hyw-embed"
version = "0.1.0"
readme = "README.md"
description = "Creating embeddings for hyw"
keywords = []
categories = []
edition.workspace = true
include.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
hyw = { path = "../hyw", version = "0.1.0" }
hyw-base = { path = "../hyw-base", version = "0.1.0" }

[[bin]]
name = "hyw-embed"
required-features = ["cli"]

[features]
cli = []

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"
disabled-strategies = ["quick-install"]

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"
