[workspace]
resolver = "2"
members = [ "hyw", "hyw-base", "hyw-embed" ]

[workspace.package]
edition = "2024"
include = ["/src", "README.md"]
repository = "https://github.com/PRO-2684/hyw"
license = "MIT"
authors = ["PRO-2684"]
